#!/bin/bash
#===============================================================================
# Lobster Staging Entrypoint
#
# Starts the lobster-router (Telegram bot) and the Claude persistent session
# inside this container, then tails the logs so the container stays alive.
#
# Required environment variables (passed via docker-compose):
#   TELEGRAM_BOT_TOKEN     - Test bot token
#   TELEGRAM_ALLOWED_USERS - Allowed Telegram user IDs (comma-separated)
#   LOBSTER_DEBUG          - Set to false for headless mode
#===============================================================================

set -euo pipefail

LOBSTER_DIR="/home/lobster/lobster"
WORKSPACE_DIR="/home/lobster/lobster-workspace"
MESSAGES_DIR="/home/lobster/messages"
CONFIG_DIR="/home/lobster/lobster-config"
LOG_DIR="$WORKSPACE_DIR/logs"

# Ensure the claude binary from the host mount is in PATH
export PATH="/home/lobster/.local/bin:/usr/local/bin:$PATH"

echo "[staging] Starting Lobster staging instance..."
echo "[staging] Claude version: $(claude --version 2>&1 || echo 'not found')"

# Fix execute bits on scripts (git sometimes strips them)
chmod +x "$LOBSTER_DIR/scripts/"*.sh 2>/dev/null || true
chmod +x "$LOBSTER_DIR/scripts/"*.exp 2>/dev/null || true

#-------------------------------------------------------------------------------
# Fix #366: Symlink .claude/ bootup files so Claude loads behavioral context.
# The .claude/ dir is volume-mounted from the host (credentials), but the
# bootup .md files live in the repo. Symlink each .md into ~/.claude/ so
# they are discoverable without running install.sh.
#-------------------------------------------------------------------------------
echo "[staging] Setting up .claude/ bootup files..."
mkdir -p /home/lobster/.claude
for md_file in "$LOBSTER_DIR/.claude/"*.md; do
    [ -e "$md_file" ] || continue
    fname=$(basename "$md_file")
    if [ ! -e "/home/lobster/.claude/$fname" ]; then
        ln -sf "$md_file" "/home/lobster/.claude/$fname"
        echo "[staging]   linked .claude/$fname"
    fi
done

#-------------------------------------------------------------------------------
# Fix #367: Symlink CLAUDE.md into lobster-workspace so Claude finds it
# explicitly rather than relying on directory-traversal fallback.
#-------------------------------------------------------------------------------
echo "[staging] Symlinking CLAUDE.md into workspace..."
ln -sf "$LOBSTER_DIR/CLAUDE.md" "$WORKSPACE_DIR/CLAUDE.md"

#-------------------------------------------------------------------------------
# Fix #368: Force-reinstall sqlite-vec on aarch64 to get the correct 64-bit
# wheel. pip sometimes resolves the armv7/armhf (ELFCLASS32) wheel on ARM64
# hosts, causing VectorMemory to fail with an ELF class mismatch at load time.
#-------------------------------------------------------------------------------
ARCH=$(uname -m)
if [ "$ARCH" = "aarch64" ]; then
    echo "[staging] aarch64 detected — reinstalling sqlite-vec for correct ABI..."
    "$LOBSTER_DIR/.venv/bin/pip" install sqlite-vec --force-reinstall --quiet \
        || echo "[staging] WARNING: sqlite-vec reinstall failed (VectorMemory may fall back to file-based)"
fi

#-------------------------------------------------------------------------------
# Write config.env from environment variables
#-------------------------------------------------------------------------------
mkdir -p "$CONFIG_DIR"
cat > "$CONFIG_DIR/config.env" << CONFIG
# Lobster Staging Config - generated by entrypoint-staging.sh
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
TELEGRAM_ALLOWED_USERS=${TELEGRAM_ALLOWED_USERS}
LOBSTER_DEBUG=${LOBSTER_DEBUG:-false}
CONFIG

echo "[staging] Config written to $CONFIG_DIR/config.env"

#-------------------------------------------------------------------------------
# Initialize state file
#-------------------------------------------------------------------------------
mkdir -p "$MESSAGES_DIR/config"
echo '{"phase":"STOPPED","started_at":null,"session_id":null}' > "$MESSAGES_DIR/config/lobster-state.json"

#-------------------------------------------------------------------------------
# Register MCP server with Claude
# The credentials are mounted from the host, but MCP config may need updating
# to point to this container's inbox_server.py path.
#-------------------------------------------------------------------------------
SETTINGS_FILE="/home/lobster/.claude/settings.json"
if [[ -f "$SETTINGS_FILE" ]]; then
    # Update the lobster-inbox MCP command path in a temp copy
    python3 - << PYEOF
import json, sys

with open("$SETTINGS_FILE") as f:
    settings = json.load(f)

# Ensure mcpServers section exists and lobster-inbox is up to date
if "mcpServers" not in settings:
    settings["mcpServers"] = {}

settings["mcpServers"]["lobster-inbox"] = {
    "command": "$LOBSTER_DIR/.venv/bin/python",
    "args": ["$LOBSTER_DIR/src/mcp/inbox_server.py"],
    "env": {
        "LOBSTER_MESSAGES": "$MESSAGES_DIR",
        "LOBSTER_WORKSPACE": "$WORKSPACE_DIR",
        "LOBSTER_INSTALL_DIR": "$LOBSTER_DIR"
    }
}

with open("$SETTINGS_FILE", "w") as f:
    json.dump(settings, f, indent=4)

print("[staging] Updated MCP settings for lobster-inbox")
PYEOF
fi

#-------------------------------------------------------------------------------
# Start the lobster-router (Telegram bot)
#-------------------------------------------------------------------------------
echo "[staging] Starting lobster-router..."
export LOBSTER_MESSAGES="$MESSAGES_DIR"
export LOBSTER_WORKSPACE="$WORKSPACE_DIR"
export LOBSTER_INSTALL_DIR="$LOBSTER_DIR"
export LOBSTER_CONFIG_DIR="$CONFIG_DIR"
source "$CONFIG_DIR/config.env"

mkdir -p "$LOG_DIR"

"$LOBSTER_DIR/.venv/bin/python" "$LOBSTER_DIR/src/bot/lobster_bot.py" \
    > "$LOG_DIR/router.log" 2>&1 &
ROUTER_PID=$!
echo "[staging] Router started (PID $ROUTER_PID)"

# Give router a moment to connect
sleep 3
if ! kill -0 $ROUTER_PID 2>/dev/null; then
    echo "[staging] ERROR: Router failed to start. Last 20 lines of log:"
    tail -20 "$LOG_DIR/router.log"
    exit 1
fi
echo "[staging] Router is running."

#-------------------------------------------------------------------------------
# Start the Claude session in tmux
#-------------------------------------------------------------------------------
echo "[staging] Starting Claude session in tmux..."

unset CLAUDECODE

tmux -L lobster new-session -d -s lobster -c "$WORKSPACE_DIR" \
    "LOBSTER_MESSAGES=$MESSAGES_DIR \
     LOBSTER_WORKSPACE=$WORKSPACE_DIR \
     LOBSTER_INSTALL_DIR=$LOBSTER_DIR \
     LOBSTER_CONFIG_DIR=$CONFIG_DIR \
     LOBSTER_MAIN_SESSION=1 \
     CLAUDE_CODE_SUBAGENT_MODEL=sonnet \
     PATH=/home/lobster/.local/bin:/usr/local/bin:/usr/bin:/bin \
     $LOBSTER_DIR/scripts/start-claude.sh 2>&1 | tee $LOG_DIR/claude.log"

echo "[staging] Claude session started in tmux."

#-------------------------------------------------------------------------------
# Wait and tail logs
#-------------------------------------------------------------------------------
echo ""
echo "[staging] =============================================="
echo "[staging] Lobster staging is running."
echo "[staging] Bot token: ${TELEGRAM_BOT_TOKEN:0:20}..."
echo "[staging] Tail logs: sudo docker exec lobster-staging tail -f $LOG_DIR/router.log"
echo "[staging] Attach:    sudo docker exec -it lobster-staging tmux -L lobster attach -t lobster"
echo "[staging] =============================================="
echo ""

# Keep container alive; exit if router dies
tail -f "$LOG_DIR/router.log" "$LOG_DIR/claude.log" 2>/dev/null &

# Monitor router process
while kill -0 $ROUTER_PID 2>/dev/null; do
    sleep 10
done

echo "[staging] Router process (PID $ROUTER_PID) died. Exiting."
exit 1
