#!/bin/bash
#===============================================================================
# Lobster Container Init — runs once at systemd boot as a oneshot service
#
# Responsibilities:
#   1. Write config.env from environment variables injected by docker-compose.
#      The docker-compose env_file (config.staging.env) sets TELEGRAM_BOT_TOKEN,
#      LOBSTER_ENV, etc. — this script materialises them into the file that the
#      lobster systemd services load via EnvironmentFile=.
#
#   2. GitHub auth — wire GITHUB_TOKEN into all 4 layers so gh CLI works in
#      every subprocess context (systemd services, tmux, Claude Code subagents).
#      docker-compose environment: passthrough reaches PID 1 only; this step
#      propagates the token to /etc/environment, gh auth login, shell profiles,
#      and config.env so all spawned processes can authenticate.
#
#   3. Run install.sh --container-setup for runtime setup:
#      - Verifies sqlite-vec loads correctly
#      - Creates stub user-config agent files
#      - Seeds canonical memory templates (idempotent)
#      - Writes ~/.claude/settings.json with all hooks (self-contained — no host
#        .claude bind-mount required)
#
#   4. Update ~/.claude/settings.json MCP registration to point at the inbox
#      server running in this container (the host settings.json path is correct,
#      but this is idempotent and ensures it's always current).
#
# This script runs as the lobster user (see lobster-container-init.service).
# It must complete before lobster-router/lobster-claude/lobster-mcp-local start.
#===============================================================================

set -euo pipefail

LOBSTER_DIR="/home/lobster/lobster"
WORKSPACE_DIR="/home/lobster/lobster-workspace"
MESSAGES_DIR="/home/lobster/messages"
CONFIG_DIR="/home/lobster/lobster-config"
LOG_DIR="$WORKSPACE_DIR/logs"

export PATH="/home/lobster/.local/bin:/usr/local/bin:/usr/bin:/bin"

echo "[container-init] Starting..."

#-------------------------------------------------------------------------------
# 1. Write config.env from environment variables
#
# docker-compose env_file injects TELEGRAM_BOT_TOKEN, LOBSTER_ENV, etc. into
# the container environment. The lobster systemd services load config.env via
# EnvironmentFile=, so we materialise the runtime values here.
#
# LOBSTER_ENV must be "production" — the dispatcher exits immediately if it is
# not. The staging config.staging.env.example documents this requirement.
#-------------------------------------------------------------------------------
mkdir -p "$CONFIG_DIR"
LOG_FILE="$LOG_DIR/container-init.log"
mkdir -p "$LOG_DIR"

# Always overwrite config.env from environment variables on every boot.
# A skip-if-exists guard here caused a production outage: when config.staging.env
# changed (e.g. a new TELEGRAM_BOT_TOKEN), the persistent volume still held the
# old config.env and the container silently used stale values. config.env is cheap
# to regenerate — always write it from the injected environment.
echo "[container-init] Writing config.env from environment..."
cat > "$CONFIG_DIR/config.env" << CONFIG
# Lobster Staging Config — generated by lobster-container-init.sh
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
TELEGRAM_ALLOWED_USERS=${TELEGRAM_ALLOWED_USERS:-}
LOBSTER_ADMIN_CHAT_ID=${LOBSTER_ADMIN_CHAT_ID:-${TELEGRAM_ALLOWED_USERS:-}}
LOBSTER_ENV=${LOBSTER_ENV:-production}
LOBSTER_DEBUG=${LOBSTER_DEBUG:-false}
GITHUB_TOKEN=${GITHUB_TOKEN:-}
# ^ Passed via docker-compose environment: (from host shell) or config.staging.env.
#   Writing it here (layer 4) ensures Lobster services that source config.env
#   also have access. Layers 1–3 are set up in the GitHub auth section below.
CONFIG
echo "[container-init] config.env written."

#-------------------------------------------------------------------------------
# 2. GitHub auth — wire GITHUB_TOKEN into all 4 layers
#
# docker-compose environment: passthrough injects GITHUB_TOKEN into PID 1, but
# subprocesses launched later (tmux sessions, Claude Code forks) do not inherit
# it. We write it into 4 durable locations so it survives shell re-launches and
# is available regardless of how the subprocess was spawned.
#
# Layer 1: /etc/environment — system-wide, read by PAM for all sessions
# Layer 2: gh auth login   — persistent ~/.config/gh/hosts.yml; most reliable
# Layer 3: ~/.bashrc / ~/.profile — interactive and login shells
# Layer 4: config.env      — already written above; sourced by Lobster services
#
# All layers are idempotent: stale entries are removed before writing so
# container restarts do not accumulate duplicate lines.
#-------------------------------------------------------------------------------
if [ -n "${GITHUB_TOKEN:-}" ]; then
    echo "[container-init] GITHUB_TOKEN detected — configuring gh CLI auth (4 layers)..."

    # Layer 1: /etc/environment (system-wide, all processes)
    # Strip any stale entries first to keep the file clean across restarts.
    # /etc/environment is root-owned; lobster has passwordless sudo in this container.
    grep -v "^GITHUB_TOKEN=\|^GH_TOKEN=" /etc/environment > /tmp/etc-environment.tmp 2>/dev/null || true
    printf 'GITHUB_TOKEN=%s\nGH_TOKEN=%s\n' "${GITHUB_TOKEN}" "${GITHUB_TOKEN}" >> /tmp/etc-environment.tmp
    sudo cp /tmp/etc-environment.tmp /etc/environment
    rm -f /tmp/etc-environment.tmp
    echo "[container-init]   Layer 1 (/etc/environment) done."

    # Layer 2: gh auth login — writes ~/.config/gh/hosts.yml
    # Most durable: gh reads this file regardless of environment variables.
    # Runs as root here; the lobster user's HOME is /home/lobster (lobster-
    # container-init.service sets User=lobster, so HOME is already correct).
    if command -v gh >/dev/null 2>&1; then
        echo "${GITHUB_TOKEN}" | gh auth login --with-token 2>/dev/null && \
            echo "[container-init]   Layer 2 (gh auth login) done." || \
            echo "[container-init]   Layer 2 (gh auth login) failed — gh may not be installed yet."
    else
        echo "[container-init]   Layer 2 skipped — gh not found in PATH."
    fi

    # Layer 3: shell profiles (interactive + login shells)
    # Strip stale exports first; append fresh ones.
    HOME_DIR="/home/lobster"
    for profile in "$HOME_DIR/.bashrc" "$HOME_DIR/.profile"; do
        touch "$profile"
        # Remove old export lines, then append updated ones.
        grep -v "^export GITHUB_TOKEN=\|^export GH_TOKEN=" "$profile" > /tmp/profile.tmp 2>/dev/null || true
        printf 'export GITHUB_TOKEN=%s\nexport GH_TOKEN=%s\n' \
            "${GITHUB_TOKEN}" "${GITHUB_TOKEN}" >> /tmp/profile.tmp
        cp /tmp/profile.tmp "$profile"
        chown lobster:lobster "$profile"
    done
    rm -f /tmp/profile.tmp
    echo "[container-init]   Layer 3 (.bashrc/.profile) done."

    # Layer 4: already written to config.env above.
    echo "[container-init]   Layer 4 (config.env) already done."

    echo "[container-init] GitHub auth configured across all 4 layers."
else
    echo "[container-init] GITHUB_TOKEN not set — skipping gh CLI auth setup."
    echo "[container-init]   To enable gh CLI in the container, set GITHUB_TOKEN in"
    echo "[container-init]   config.staging.env or export it in your host shell before"
    echo "[container-init]   running docker compose."
fi

#-------------------------------------------------------------------------------
# 3. Run install.sh --container-setup (renumbered from 2 after adding gh auth)
#
# Idempotent — safe to run on every boot. Handles:
#   - sqlite-vec load verification
#   - CLAUDE.md and .claude/ symlinks
#   - Stub user-config agent files
#   - Canonical memory template seeding
#   - lobster-state.json seeding with booted_at
#   - ~/.claude/settings.json with all hooks (makes the image self-contained)
#-------------------------------------------------------------------------------
echo "[container-init] Running install.sh --container-setup..."
LOBSTER_INSTALL_DIR="$LOBSTER_DIR" \
LOBSTER_WORKSPACE="$WORKSPACE_DIR" \
LOBSTER_MESSAGES="$MESSAGES_DIR" \
LOBSTER_CONFIG_DIR="$CONFIG_DIR" \
    bash "$LOBSTER_DIR/install.sh" --container-setup 2>&1 | tee -a "$LOG_FILE" || true
echo "[container-init] Container setup complete."

#-------------------------------------------------------------------------------
# 4. Update Claude settings.json MCP registration
#
# install.sh --container-setup writes settings.json with all hooks.
# The Dockerfile also pre-registers the MCP server via `claude mcp add`.
# This step is a safety net: if the workspace volume already has an older
# settings.json that pre-dates the hooks (e.g. from a previous container run),
# register the MCP server to ensure it is present.
#-------------------------------------------------------------------------------
SETTINGS_FILE="/home/lobster/.claude/settings.json"
if [ -f "$SETTINGS_FILE" ]; then
    if ! python3 -c "import json; d=json.load(open('$SETTINGS_FILE')); exit(0 if 'lobster-inbox' in str(d) else 1)" 2>/dev/null; then
        echo "[container-init] MCP registration not found in settings.json — registering..."
        /home/lobster/.local/bin/claude mcp add --transport http lobster-inbox \
            -s user http://localhost:8766/mcp 2>/dev/null || true
    else
        echo "[container-init] MCP registration present — skipping."
    fi
fi

echo "[container-init] Done."
